name: PLE7
options:
  bundleIdPrefix: com.ple7
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  WireGuardKit:
    url: https://github.com/WireGuard/wireguard-apple
    from: "1.0.16"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"

targets:
  PLE7:
    type: application
    platform: iOS
    sources:
      - path: PLE7
      - path: Shared
    entitlements:
      path: PLE7/PLE7.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.ple7.vpn
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.developer.networking.vpn.api:
          - allow-vpn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ple7.vpn
        INFOPLIST_FILE: PLE7/Info.plist
        CODE_SIGN_ENTITLEMENTS: PLE7/PLE7.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
    dependencies:
      - target: PacketTunnel
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
      - package: KeychainAccess
    postBuildScripts:
      - name: "Embed WireGuard Go"
        script: |
          ${BUILD_DIR%Build/*}SourcePackages/checkouts/wireguard-apple/Sources/WireGuardKitGo/make_go_bridge.sh

  PacketTunnel:
    type: app-extension
    platform: iOS
    sources:
      - path: PacketTunnel
      - path: Shared
    entitlements:
      path: PacketTunnel/PacketTunnel.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.ple7.vpn
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ple7.vpn.PacketTunnel
        INFOPLIST_FILE: PacketTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: PacketTunnel/PacketTunnel.entitlements
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: YES
    dependencies:
      - package: WireGuardKit
        product: WireGuardKit
      - package: KeychainAccess
